"""empty message

Revision ID: 57744cb991f6
Revises: b2b7f2fe2191
Create Date: 2022-05-19 13:41:47.697352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57744cb991f6'
down_revision = 'b2b7f2fe2191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'date')
    # ### end Alembic commands ###
