"""empty message

Revision ID: 852f785c711a
Revises: 57744cb991f6
Create Date: 2022-05-19 13:43:08.219039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852f785c711a'
down_revision = '57744cb991f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'date')
    # ### end Alembic commands ###
